include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
  # implitic-cast: false
  # implitic-dynamic: false

linter:
  rules:
    # - prefer_const_constructors
    # - prefer_const_declaration
    - avoid_print
    - use_key_in_widget_constructors
    - always_use_package_imports